<?php

namespace App\Controllers;

use App\Models\EventModel;
use App\Models\RegistrationModel;
use App\Models\UserModel;

class User extends BaseController
{
    public function dashboard()
    {
        $eventModel = new EventModel();
        $registrationModel = new RegistrationModel();

        $userId = session()->get('id');

        // Fetch all events
        $events = $eventModel->findAll();

        $registeredEvents = [];
        if ($userId) {
            // Fetch all registration records
            $userRegs = $registrationModel->where('user_id', $userId)->findAll();
            foreach ($userRegs as $reg) {
                // Store the whole registration record
                // This will automatically include 'certificate_published' and 'certificate_path'
                // This function does NOT need changes.
                $registeredEvents[$reg['event_id']] = $reg;
            }
        }

        return view('user/dashboard', [
            'events' => $events,
            'registeredEvents' => $registeredEvents
        ]);
    }

    public function registerEvent($eventId)
    {
        $session = session();

        // Check if user is logged in
        if (!$session->has('id')) {
            return redirect()->to('/auth/login')->with('error', 'Please log in first.');
        }

        $userId = $session->get('id');
        $registrationModel = new RegistrationModel();

        // Prevent duplicate registrations
        $existing = $registrationModel
            ->where('user_id', $userId)
            ->where('event_id', $eventId)
            ->first();

        if ($existing) {
            return redirect()
                ->to('user/dashboard')
                ->with('info', 'You are already registered for this event.');
        }

        // Insert registration
        $registrationModel->insert([
            'user_id'    => $userId,
            'event_id'   => $eventId,
            // 'certificate_ready' etc. default to 0
            'created_at' => date('Y-m-d H:i:s'),
        ]);

        return redirect()
            ->to('user/dashboard')
            ->with('success', 'Successfully registered for the event.');
    }
    
    // User views list of completed events for certificate download
    public function certificates()
    {
        $session = session();
        if (!$session->has('id')) {
            return redirect()->to('/auth/login')->with('error', 'Please log in first.');
        }

        $userId = $session->get('id');
        $db = \Config\Database::connect();

        // Join registrations with events
        $registrations = $db->table('registrations')
            // --- CHANGED --- : Added certificate_published and certificate_path
            ->select('registrations.event_id, registrations.certificate_published, registrations.certificate_path, events.title, events.date')
            ->join('events', 'events.id = registrations.event_id')
            ->where('registrations.user_id', $userId)
            // --- CHANGED --- : Check if 'certificate_published' is 1
            ->where('registrations.certificate_published', 1)
            ->get()
            ->getResultArray();

        return view('user/certificates', [
            'title' => 'My Certificates',
            'certificates' => $registrations,
        ]);
    }

    // --- CHANGED --- : Renamed function to downloadCertificate
    // This function now downloads the PDF file generated by the Coordinator
    public function downloadCertificate($eventId)
    {
        $session = session();
        if (!$session->has('id')) {
            return redirect()->to('/auth/login')->with('error', 'Please log in first.');
        }

        $userId = $session->get('id');
        $registrationModel = new RegistrationModel();

        // 1. Check Registration and if it's published
        $registration = $registrationModel
            ->where('user_id', $userId)
            ->where('event_id', $eventId)
            ->first();

        // --- CHANGED --- : Updated the check
        if (empty($registration) || $registration['certificate_published'] != 1 || empty($registration['certificate_path'])) {
            return redirect()
                ->to('user/certificates')
                ->with('error', 'Certificate not available. It may not be published by the coordinator yet.');
        }

        // 2. Get the file path
        $filePath = $registration['certificate_path'];

        // 3. Check if the file actually exists on the server
        if (!file_exists($filePath)) {
            log_message('error', 'Certificate file not found at path: ' . $filePath);
            return redirect()->back()->with('error', 'Certificate file not found. Please contact the coordinator.');
        }

        // 4. Trigger a force download
        return $this->response->download($filePath, null);
    }
    
    // ** Unchanged methods below **
    public function editProfile()
    {
        $session = session();

        if (!$session->get('isLoggedIn')) {
            return redirect()->to('/auth/login');
        }

        $userModel = new UserModel();
        $userId = $session->get('id');
        $user = $userModel->find($userId);

        return view('user/profile', [
            'title' => 'Edit Profile',
            'user' => $user,
        ]);
    }

    public function updateProfile()
    {
        $session = session();
        
        if (!$session->get('isLoggedIn')) {
            return redirect()->to('/auth/login');
        }

        $userId = $session->get('id');
        $userModel = new UserModel();

        // 1. Define Validation Rules
        $rules = [
            'email' => "required|max_length[255]|valid_email|is_unique[users.email,id,{$userId}]",
            'phone' => 'required|max_length[15]',
            'class' => 'required|max_length[50]',
        ];

        // Check if the user entered a new password
        if ($this->request->getPost('password') !== '') {
            $rules['password'] = 'required|min_length[8]';
            $rules['password_confirm'] = 'required_with[password]|matches[password]';
        }

        // 2. Validate the Request
        if (!$this->validate($rules)) {
            $user = $userModel->find($userId);
            return view('user/profile', [
                'validation' => $this->validator,
                'user' => $user
            ]);
        }

        // 3. Prepare Data for Update
        $data = [
            'email' => $this->request->getPost('email'),
            'phone' => $this->request->getPost('phone'),
            'class' => $this->request->getPost('class'),
        ];

        // Handle Password Update (only if a new password was provided)
        $newPassword = $this->request->getPost('password');
        if (!empty($newPassword)) {
            $data['password'] = $newPassword;
        }

        // 4. Update the User Record
        if ($userModel->update($userId, $data)) {
            $session->set('userEmail', $data['email']);

            return redirect()->to('user/profile')->with('success', 'Profile updated successfully!');
        } else {
            return redirect()->to('user/profile')->with('error', 'Failed to update profile due to a database error.');
        }
    }
}